version: "3.4"

# Used to spin up the Queue and database services only
#     restart: always
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: DEV_USER
      RABBITMQ_DEFAULT_PASS: CHANGE_ME
    logging:
      driver: local

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: DEV_USER
      MONGO_INITDB_ROOT_PASSWORD: CHANGE_ME
      MONGO_INITDB_DATABASE: pavai

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: DEV_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: CHANGE_ME
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: DEV_USER
      ME_CONFIG_BASICAUTH_PASSWORD: CHANGE_ME
    depends_on:
      - mongo
    logging:
      driver: local
