[tool.poetry]
name = "vocei_app"
version = "0.1.0"
description = ""
authors = ["mychen76 <mychen76@gmail.com>"]
license = ""

packages = []

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
